"""rename plugin filter column

Revision ID: 566709537515
Revises: d4c27044618e
Create Date: 2023-08-28 11:09:54.087308

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "566709537515"
down_revision = "d4c27044618e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("TemplateTab", schema=None) as batch_op:
        batch_op.add_column(sa.Column("filter_string", sa.Text(), nullable=True))
        batch_op.drop_column("plugin_filter")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("TemplateTab", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plugin_filter", sa.TEXT(), nullable=True))
        batch_op.drop_column("filter_string")

    # ### end Alembic commands ###
