"""add schema url and tab metadata

Revision ID: 589288818739
Revises: bf584f934a0e
Create Date: 2026-03-03 11:08:46.053428

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "589288818739"
down_revision = "bf584f934a0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("RAMP", schema=None) as batch_op:
        batch_op.add_column(sa.Column("schema_url", sa.Text(), nullable=True))

    with op.batch_alter_table("TemplateTab", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("meta", sa.JSON(), nullable=False, server_default="{}")
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("TemplateTab", schema=None) as batch_op:
        batch_op.drop_column("meta")

    with op.batch_alter_table("RAMP", schema=None) as batch_op:
        batch_op.drop_column("schema_url")
    # ### end Alembic commands ###
